"""Create Message

Revision ID: ff19733b50fc
Revises: baf9a7b2da13
Create Date: 2021-01-05 17:09:47.622946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff19733b50fc'
down_revision = 'baf9a7b2da13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('update_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id_sender', sa.Integer(), nullable=False),
    sa.Column('id_recipient', sa.Integer(), nullable=False),
    sa.Column('content_message', sa.VARCHAR(length=4096), nullable=True),
    sa.ForeignKeyConstraint(['id_recipient'], ['users.id'], ),
    sa.ForeignKeyConstraint(['id_sender'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
